name: AWS Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      ## gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: application.properties setting
        run: |
          cd ./src/main/resources
          cat <<EOF > application.properties
          ${{ secrets.APPLICATION_PROPERTIES }}
          EOF

      - name: Build with Gradle
        run: ./gradlew build -x test

